export const roles = {
  ADMIN: 'ADMIN',
  BOARD_MEMBER: 'BOARD_MEMBER',
  RUN_LEADER: 'RUN_LEADER',
  FULL_MEMBER: 'FULL_MEMBER',
  EMERITUS_MEMBER: 'EMERITUS_MEMBER',
  ASSOCIATE_MEMBER: 'ASSOCIATE_MEMBER',
  GUEST_MEMBER: 'GUEST_MEMBER',
};

export const statuses = {
  ACTIVE: 'ACTIVE',
  PAST_DUE: 'PAST_DUE',
  DELINQUENT: 'DELINQUENT',
  REMOVED: 'REMOVED',
  RESIGNED: 'RESIGNED',
  INACTIVE: 'INACTIVE',
  LOCKED: 'LOCKED',
};
